# Generated by Django 5.1.6 on 2025-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
